from typing import Any


COLOR = "\u00a7"

OBJECTIVE_TYPES = [
    "craft",
    "enchant",
    "place",
    "break",
    "player_kill",
    "mob_kill",
    "walk",
    "trade",
    "tame",
    "smith",
    "smelt",
    "shear",
    "fish",
    "deal_damage",
    "consume",
    "brew",
    "breed",
]

OBJECTIVE_ALIASES = {
    "crafting": "craft",
    "crafted": "craft",
    "enchanting": "enchant",
    "enchanted": "enchant",
    "place_blocks": "place",
    "place_block": "place",
    "placing": "place",
    "break_blocks": "break",
    "break_block": "break",
    "breaking": "break",
    "playerkill": "player_kill",
    "playerkills": "player_kill",
    "playerkilling": "player_kill",
    "player_killing": "player_kill",
    "kill_player": "player_kill",
    "mobkill": "mob_kill",
    "mobkills": "mob_kill",
    "mobkilling": "mob_kill",
    "mob_killing": "mob_kill",
    "kill_mob": "mob_kill",
    "walking": "walk",
    "distance": "walk",
    "trading": "trade",
    "tamin": "tame",
    "taming": "tame",
    "smithing": "smith",
    "smelting": "smelt",
    "cooking": "smelt",
    "shearing": "shear",
    "fishing": "fish",
    "dealdamage": "deal_damage",
    "deal_damage": "deal_damage",
    "damage": "deal_damage",
    "consume_item": "consume",
    "consuming": "consume",
    "brewing": "brew",
    "breeding": "breed",
}

EVENT_OBJECTIVE_TYPES = {
    "break",
    "place",
    "player_kill",
    "mob_kill",
    "walk",
    "smelt",
    "tame",
    "shear",
    "fish",
    "deal_damage",
    "consume",
    "breed",
}


def default_quests() -> dict[str, Any]:
    return {
        "schema_version": 1,
        "quests": {
            "getting_started": {
                "enabled": True,
                "auto_start": True,
                "repeatable": False,
                "display_name": "&dGetting Started",
                "description": "&7Gather wood and place your first blocks.",
                "objectives": [
                    {
                        "id": "break_logs",
                        "type": "break",
                        "target": "minecraft:oak_log",
                        "amount": 8,
                        "description": "Break 8 oak logs",
                    },
                    {
                        "id": "place_cobble",
                        "type": "place",
                        "target": "minecraft:cobblestone",
                        "amount": 8,
                        "description": "Place 8 cobblestone",
                    },
                ],
                "rewards": {
                    "items": [
                        {"type": "minecraft:bread", "amount": 6},
                    ],
                    "exp": 50,
                },
            },
            "stretch_your_legs": {
                "enabled": True,
                "auto_start": True,
                "repeatable": False,
                "display_name": "&dStretch Your Legs",
                "description": "&7Explore a little.",
                "objectives": [
                    {
                        "id": "walk_150",
                        "type": "walk",
                        "amount": 150,
                        "description": "Walk 150 blocks",
                    },
                ],
                "rewards": {
                    "items": [
                        {"type": "minecraft:torch", "amount": 12},
                    ],
                    "exp": 50,
                },
            },
            "first_hunt": {
                "enabled": True,
                "auto_start": True,
                "repeatable": False,
                "display_name": "&dFirst Hunt",
                "description": "&7Fight your first mobs.",
                "objectives": [
                    {
                        "id": "kill_zombies",
                        "type": "mob_kill",
                        "target": "minecraft:zombie",
                        "amount": 3,
                        "description": "Kill 3 zombies",
                    },
                    {
                        "id": "deal_damage",
                        "type": "deal_damage",
                        "amount": 30,
                        "description": "Deal 30 damage",
                    },
                ],
                "rewards": {
                    "items": [
                        {"type": "minecraft:iron_ingot", "amount": 4},
                    ],
                    "exp": 75,
                },
            },
        },
    }


def default_config() -> dict[str, Any]:
    return {
        "settings": {
            "prefix": "&dQuests &8> &r",
            "auto_start_enabled": False,
            "show_progress_messages": False,
            "show_objective_complete_messages": True,
            "progress_message_min_interval_seconds": 3,
            "walk_min_distance": 0.05,
            "walk_max_distance_per_event": 5.0,
            "smelt_credit_seconds": 600,
        },
        "messages": {
            "error.players_only": "&cOnly players can use this command.",
            "error.no_permission": "&cYou do not have permission to do that.",
            "error.unknown_command": "&cUnknown command. Use &f/quests help&c.",
            "error.usage": "&cUsage: &f{usage}",
            "error.quest_missing": "&cQuest &f{quest}&c does not exist.",
            "error.quest_disabled": "&cQuest &f{quest}&c is disabled.",
            "error.quest_active": "&cYou are already working on &f{name}&c.",
            "error.quest_not_active": "&cYou are not working on &f{name}&c.",
            "error.quest_completed": "&cYou already completed &f{name}&c.",
            "error.player_missing": "&cPlayer &f{player}&c is not online.",
            "error.invalid_amount": "&cAmount must be a positive number.",
            "error.invalid_type": "&cUnknown objective type &f{type}&c.",
            "quest.help.header": "&d&lQuests",
            "quest.help.menu": "&7/quests &8- &fOpen the quest menu",
            "quest.help.list": "&7/quests list &8- &fList available quests",
            "quest.help.start": "&7/quests start <quest> &8- &fStart a quest",
            "quest.help.progress": "&7/quests progress [quest] &8- &fView progress",
            "quest.help.info": "&7/quests info <quest> &8- &fView quest goals",
            "quest.help.cancel": "&7/quests cancel <quest> &8- &fCancel an active quest",
            "quest.menu.title": "&d&lQuests",
            "quest.menu.content": "&7Active: &f{active} &8| &7Available: &f{available} &8| &7Completed: &f{completed}",
            "quest.menu.all": "&fAll Quests",
            "quest.menu.active": "&eActive Quests",
            "quest.menu.available": "&bAvailable Quests",
            "quest.menu.completed": "&aCompleted Quests",
            "quest.menu.all.title": "&d&lAll Quests",
            "quest.menu.active.title": "&e&lActive Quests",
            "quest.menu.available.title": "&b&lAvailable Quests",
            "quest.menu.completed.title": "&a&lCompleted Quests",
            "quest.menu.select": "&7Select a quest to view details.",
            "quest.menu.no_quests": "&7No quests in this view.",
            "quest.menu.back": "&8Back",
            "quest.menu.start": "&aStart Quest",
            "quest.menu.cancel": "&cCancel Quest",
            "quest.menu.status.active": "&eActive",
            "quest.menu.status.completed": "&aCompleted",
            "quest.menu.status.available": "&bAvailable",
            "quest.menu.quest_button": "{status}: {name}\n{summary}",
            "quest.menu.summary.active": "&7{completed}/{total} objectives ({percent}%)",
            "quest.menu.summary.available": "&7Not started",
            "quest.menu.summary.completed": "&7Completed {times}x",
            "quest.menu.summary.no_objectives": "&7No objectives",
            "quest.menu.detail.status": "&7Status: &f{status}",
            "quest.menu.detail.objectives": "&dObjectives",
            "quest.menu.detail.rewards": "&dRewards",
            "quest.menu.objective": "&7- &f{description} &8(&d{progress}&7/&d{amount}&8)",
            "quest.menu.no_objectives": "&7No objectives.",
            "quest.menu.reward.item": "&7- &f{amount}x {item}",
            "quest.menu.reward.exp": "&7- &f{exp} XP",
            "quest.menu.reward.levels": "&7- &f{levels} XP levels",
            "quest.menu.reward.commands": "&7- &f{commands} command reward(s)",
            "quest.list.header": "&d&lAvailable Quests",
            "quest.list.entry": "&7- &f{id} &8({name}&8) &7- &f{status}",
            "quest.list.none": "&7No quests are enabled yet.",
            "quest.info.header": "&d&l{name}",
            "quest.info.description": "&7{description}",
            "quest.info.objective": "&7- &f{description} &8(&d{amount}&8)",
            "quest.started": "&aStarted quest &f{name}&a.",
            "quest.cancelled": "&eCancelled quest &f{name}&e.",
            "quest.progress.header": "&d&l{name}",
            "quest.progress.objective": "&7- &f{description}&7: &d{progress}&7/&d{amount}",
            "quest.progress.none": "&7You do not have any active quests.",
            "quest.progress": "&7{name}: &f{description} &d{progress}&7/&d{amount}",
            "quest.objective_complete": "&aObjective complete: &f{description}&a.",
            "quest.complete": "&aQuest complete: &f{name}&a!",
            "quest.auto_started": "&aStarted quest &f{name}&a.",
            "admin.help.header": "&d&lQuest Admin",
            "admin.help.reload": "&7/questadmin reload",
            "admin.help.list": "&7/questadmin list",
            "admin.help.progress": "&7/questadmin progress <player> <type> <amount> [target]",
            "admin.help.reset": "&7/questadmin reset <player> [quest]",
            "admin.help.complete": "&7/questadmin complete <player> <quest>",
            "admin.reload": "&aQuest config and player data reloaded.",
            "admin.progress": "&aAdded &f{amount} &aprogress for &f{type} &ato &f{player}&a.",
            "admin.reset": "&aReset quest progress for &f{player}&a.",
            "admin.complete": "&aCompleted &f{quest} &afor &f{player}&a.",
        },
    }
